name: Node.js CI - Frontend

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    # Checkout the repository
    - uses: actions/checkout@v4

    # Set up Node.js globally (this sets it up for the entire runner)
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Now target your frontend subdirectory for npm commands

    # Clear npm cache in the frontend directory
    - name: Clear npm cache (Frontend)
      run: npm cache clean --force
      working-directory: ./Portfolio/Portfolio/frontend  # Use your frontend directory here

    # Install dependencies for the frontend
    - name: Install frontend dependencies
      run: npm install
      working-directory: ./Portfolio/Portfolio/frontend  # Use your frontend directory here

    # Build the frontend project
    - name: Build frontend
      run: npm run build --if-present
      working-directory: ./Portfolio/Portfolio/frontend  # Use your frontend directory here

    # Run frontend tests
    - name: Run frontend tests
      run: npm test
      working-directory: ./Portfolio/Portfolio/frontend  # Use your frontend directory here
