name: Node.js CI - Frontend

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run: 
        working-directory: frontend
      
    strategy:
      matrix:
        node-version: [22.x]

    steps:
    # Checkout the repository
    - uses: actions/checkout@v4

    # Set up Node.js globally (this sets it up for the entire runner)
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Optional: Debugging step to confirm lock file exists
    - name: Check if package-lock.json exists
      run: ls -la ./Portfolio/Portfolio/frontend/package-lock.json

    # Clear npm cache in the frontend directory
    - name: Clear npm cache (Frontend)
      run: npm cache clean --force
      working-directory: ./Portfolio/Portfolio/frontend

    # Install dependencies for the frontend
    - name: Install frontend dependencies
      run: npm install
      working-directory: ./Portfolio/Portfolio/frontend

    # Build the frontend project
    - name: Build frontend
      run: npm run build --if-present
      working-directory: ./Portfolio/Portfolio/frontend

    # Run frontend tests
    - name: Run frontend tests
      run: npm test
      working-directory: ./Portfolio/Portfolio/frontend
